### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Lissete7** [SistemasTecTlaxiaco/infografia-Lissete7#2]
[Infografia_Lizzete Leon Gonzalez.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Lissete7/files/7173224/Infografia_Lizzete.Leon.Gonzalez.pdf)

**Comment by CxrlosMX** [comment]
Trabajo muy bien realizado, cumple con todos los requerimientos. 
Calificación: 20/20

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
